// <auto-generated />
using System;
using DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.EF.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    partial class CarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.CarModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("Name", "BrandName")
                        .IsUnique();

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BrandName = "Outback",
                            IsAvailable = true,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 2L,
                            BrandName = "CR-V",
                            IsAvailable = true,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3L,
                            BrandName = "XTrail",
                            IsAvailable = true,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 4L,
                            BrandName = "Sorento",
                            IsAvailable = true,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 5L,
                            BrandName = "Santa Fe",
                            IsAvailable = true,
                            Name = "Kia"
                        });
                });

            modelBuilder.Entity("Domain.CarOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BankLoanDownPayment")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("BankLoanDuration")
                        .HasColumnType("int");

                    b.Property<decimal>("BankLoanMonthlyPayment")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<int>("GearType")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TrimName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CarOrders");
                });

            modelBuilder.Entity("Domain.CarTrim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CarModelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("CarTrims");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CarModelId = 1L,
                            IsAvailable = true,
                            Name = "Premium"
                        },
                        new
                        {
                            Id = 2L,
                            CarModelId = 1L,
                            IsAvailable = true,
                            Name = "Limited"
                        },
                        new
                        {
                            Id = 3L,
                            CarModelId = 2L,
                            IsAvailable = true,
                            Name = "LX"
                        },
                        new
                        {
                            Id = 4L,
                            CarModelId = 2L,
                            IsAvailable = true,
                            Name = "EX"
                        },
                        new
                        {
                            Id = 5L,
                            CarModelId = 2L,
                            IsAvailable = true,
                            Name = "EX-L"
                        });
                });

            modelBuilder.Entity("Domain.CarVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CarTrimId")
                        .HasColumnType("bigint");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<int>("GearType")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarTrimId");

                    b.ToTable("CarVariants");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CarTrimId = 1L,
                            Engine = "EK31",
                            FuelType = 0,
                            GearType = 0,
                            IsAvailable = true,
                            Price = 2000,
                            Year = 2014
                        },
                        new
                        {
                            Id = 2L,
                            CarTrimId = 1L,
                            Engine = "EK51",
                            FuelType = 0,
                            GearType = 0,
                            IsAvailable = true,
                            Price = 2000,
                            Year = 2014
                        },
                        new
                        {
                            Id = 3L,
                            CarTrimId = 1L,
                            Engine = "EK23",
                            FuelType = 0,
                            GearType = 0,
                            IsAvailable = true,
                            Price = 2000,
                            Year = 2014
                        },
                        new
                        {
                            Id = 4L,
                            CarTrimId = 2L,
                            Engine = "GX",
                            FuelType = 1,
                            GearType = 1,
                            IsAvailable = true,
                            Price = 2000,
                            Year = 2014
                        },
                        new
                        {
                            Id = 5L,
                            CarTrimId = 3L,
                            Engine = "V-TWIN",
                            FuelType = 1,
                            GearType = 0,
                            IsAvailable = true,
                            Price = 2000,
                            Year = 2010
                        },
                        new
                        {
                            Id = 6L,
                            CarTrimId = 3L,
                            Engine = "iGX",
                            FuelType = 0,
                            GearType = 1,
                            IsAvailable = true,
                            Price = 2000,
                            Year = 2014
                        });
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "agrynco@gmail.com",
                            Name = "Anatolii Grynchuk",
                            Phone = "01234567"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "agrynco+second_customer@gmail.com",
                            Name = "Alex Bolgarob",
                            Phone = "2345678"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "agrynco+third_customer@gmail.com",
                            Name = "Bohdan Hertz",
                            Phone = "2345678"
                        });
                });

            modelBuilder.Entity("Domain.CarOrder", b =>
                {
                    b.HasOne("Domain.Customer", "Customer")
                        .WithMany("CarOrder")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CarTrim", b =>
                {
                    b.HasOne("Domain.CarModel", "CarModel")
                        .WithMany("CarTrims")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CarVariant", b =>
                {
                    b.HasOne("Domain.CarTrim", "CarTrim")
                        .WithMany("CarVariants")
                        .HasForeignKey("CarTrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
